### ISSUE TITLE
Inline Newton iterations

### ISSUE THREAD

**Issue by adtzlr** [adtzlr/matadi#138]
In nonlinear viscoelasticity / plasticity it is sometimes required to numerically solve a dissipation / viscoelastic evolution ODE / PDE with the Newton-Rhapson method. 

### Tasks

- [ ] Outline whether it is possible to use `casadi.rootfinder(label, "newton", Function)`.

- [ ] Is it useful to provide a wrapper-function which creates the function object of a given (equilibrium) equation to solve?

- [ ] Add a test.

- [ ] Add an example.
