### ISSUE TITLE
Add Micro-sphere model for rubber elasticity

### ISSUE THREAD

**Issue by adtzlr** [adtzlr/matadi#28]
Implement the affine, non-affine, stretch and area-stretch micro-sphere models for rubber elasticity [1].

### Tasks
- [x] Add numeric integration scheme on the surface of a sphere [2] 
- [x] Add affine stretch model
- [x] Add affine tube model
- [x] Add non-affine stretch model
- [x] Add non-affine tube model
- [x] Add one-dimensional micro-sphere model (langevin and gauss model)
- [x] Add links to README
- [x] Add tests

### References

[1] C. Miehe, “A micro-macro approach to rubber-like materials. Part I: the non-affine micro-sphere model of rubber elasticity,” Journal of the Mechanics and Physics of Solids, vol. 52, no. 11. Elsevier BV, pp. 2617–2660, Nov. 2004. [![DOI:10.1016/j.jmps.2004.03.011](https://zenodo.org/badge/DOI/10.1016/j.jmps.2004.03.011.svg)](https://doi.org/10.1016/j.jmps.2004.03.011)

[2] P. Bažant and B. H. Oh, “Efficient Numerical Integration on the Surface of a Sphere,” ZAMM - Journal of Applied Mathematics and Mechanics / Zeitschrift für Angewandte Mathematik und Mechanik, vol. 66, no. 1. Wiley, pp. 37–49, 1986. [![DOI:10.1002/zamm.19860660108](https://zenodo.org/badge/DOI/10.1002/zamm.19860660108.svg)](https://doi.org/10.1002/zamm.19860660108)

**Comment by adtzlr** [comment]
The driving force of the 1d micro-sphere model has to be integrated w.r.t. the stretch, in order to obtain the 1d strain energy function. The Padé approximation of the inverse Langevin function will be integrated w.r.t. the stretch. [Here](https://www.wolframalpha.com/input/?i=integrate+%283*N+-+%CE%BB%5E2%29%2F%28N-%CE%BB%5E2%29+d%CE%BB) is the result of WolframAlpha:

```wolfram
integrate (3*N - λ^2)/(N-λ^2) dλ
```

gives:

```wolfram
λ + 2 sqrt(N) tanh^(-1)(λ/sqrt(N))
```

This is transformed into a Python function:

```python
def langevin(λ, mu, N):
    """Langevin model (Padé approximation) given by the free energy 
    of a single chain as a function of the stretch."""

    return mu * (λ + 2 * sqrt(N) * atanh(λ / sqrt(N)))
```

**Comment by adtzlr** [comment]
This is possible via e6159557341e6473f7d841f37e8d55db51a2947a:

```python
import matadi

quadrature = matadi.models.microsphere.quadrature.BazantOh(n=21)

Mat = matadi.MaterialHyperelastic(
    fun=matadi.models.microsphere.affine.stretch,
    r=quadrature.points,
    w=quadrature.weights,
    f=matadi.models.microsphere.langevin,
    bulk=5000,
    kwargs={"mu": 1.0, "N": 10}
)

lab = matadi.Lab(Mat)
data = lab.run(ux=True, bx=True, ps=True, num=50)
fig, ax = lab.plot(data, stability=True)
```

**Comment by adtzlr** [comment]
### Improvements

- [ ] Change micro-sphere function arguments from `r` and `w` to a class called `quadrature`.
